name: Generate Snake

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate snake.svg (github-dark)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: parthiv-19
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light
            dist/snake-auto.svg?palette=github-auto
            dist/snake-rainbow.svg?palette=rainbow-bright
            dist/snake-ocean.svg?palette=ocean-blue
            dist/snake-neon.svg?palette=electric-cyan

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
