name: Generate Custom Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Generate multiple themed snakes
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: parthiv-19
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark&background_color=0d1117&grid_color=21262d&empty_color=161b22&color_dots=39d353,26a641,006d32,0d4429,01311f&color_snake=00ff00
            dist/snake-light.svg?palette=github-light&background_color=ffffff&grid_color=e1e4e8&empty_color=ebedf0&color_dots=40c463,30a14e,216e39,0e4429,002e1a&color_snake=00ff00

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
